#!/usr/bin/env python3
"""Generate the deterministic provider support matrix from MarketRegistry."""
from __future__ import annotations

import argparse
import sys
from collections.abc import Mapping
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "src"
DEFAULT_OUTPUT = ROOT / "docs" / "provider-support-matrix.md"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from tradingview_zy.domain import Capability  # noqa: E402
from tradingview_zy.market_registry import (  # noqa: E402
    MARKET_REGISTRY,
    MarketSpec,
    validate_market_registry,
)


def _escape(value: Any) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ").strip()


def _capability_names(capabilities: frozenset[Capability]) -> str:
    ordered = [capability.value for capability in Capability if capability in capabilities]
    return ", ".join(f"`{name}`" for name in ordered) or "—"


def _session_summary(spec: MarketSpec) -> str:
    return "; ".join(
        f"`{name}` = `{session}`"
        for name, session in spec.tradingview_sessions.items()
    )


def render_support_matrix(
    registry: Mapping[Any, MarketSpec] = MARKET_REGISTRY,
) -> str:
    validate_market_registry(registry)
    lines = [
        "# Provider support matrix",
        "",
        "> Generated by `script/remediation/generate_provider_support_matrix.py` from",
        "> `src/tradingview_zy/market_registry.py`. Do not edit this file by hand.",
        "",
        "This matrix describes the capabilities exposed by the standard `get_exchange()`",
        "facade. A method present on a legacy SDK adapter is **not** supported unless the",
        "selected provider declares the corresponding capability below.",
        "",
        "No built-in provider declares `live_orders`; all live-order entry points remain",
        "fail-closed pending a persisted Order/Fill state machine, broker reconciliation,",
        "and sandbox acceptance.",
        "",
        "## Markets",
        "",
        "| Market | Display name | Default provider | Default code | TradingView type | Payload timezone | Sessions |",
        "|---|---|---|---|---|---|---|",
    ]
    for market, spec in registry.items():
        lines.append(
            "| "
            + " | ".join(
                (
                    f"`{_escape(market.value)}`",
                    _escape(spec.ui_label),
                    f"`{_escape(spec.default_provider)}`",
                    f"`{_escape(spec.default_code)}`",
                    f"`{_escape(spec.tradingview_type)}`",
                    f"`{_escape(spec.payload_timezone)}`",
                    _session_summary(spec),
                )
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "## Providers",
            "",
            "| Market | Provider | Default | Capabilities |",
            "|---|---|---:|---|",
        ]
    )
    for market, spec in registry.items():
        for provider_name, provider in spec.providers.items():
            lines.append(
                "| "
                + " | ".join(
                    (
                        f"`{_escape(market.value)}`",
                        f"`{_escape(provider_name)}`",
                        "yes" if provider_name == spec.default_provider else "no",
                        _capability_names(provider.capabilities),
                    )
                )
                + " |"
            )

    lines.extend(
        [
            "",
            "## Capability meanings",
            "",
            "| Capability | Contract |",
            "|---|---|",
            "| `metadata` | Default symbol and supported frequency metadata. |",
            "| `market_data` | Validated OHLCV history. |",
            "| `ticks` | Bounded current-quote lookup. |",
            "| `catalog` | Searchable symbol catalogue; not necessarily authoritative issuer metadata. |",
            "| `security_master` | Authoritative security identity/listing metadata. |",
            "| `session_status` | Strict boolean market-session status. |",
            "| `plates` | Sector/plate ownership and constituents. |",
            "| `account_balance` | Read-only account balance. |",
            "| `positions` | Read-only positions. |",
            "| `live_orders` | Live order submission; currently declared by no built-in provider. |",
            "",
            "Removed CTP and ZB providers are documented in `docs/unsupported-providers.md`",
            "and are rejected before import or cache publication.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    output = args.output.resolve()
    expected = render_support_matrix()
    if args.check:
        if not output.is_file():
            print(f"Provider support matrix is missing: {output.relative_to(ROOT)}")
            return 1
        actual = output.read_text(encoding="utf-8")
        if actual != expected:
            print(
                "Provider support matrix is stale; regenerate with "
                "python script/remediation/generate_provider_support_matrix.py"
            )
            return 1
        print("Provider support matrix is current.")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(expected, encoding="utf-8", newline="\n")
    print(f"Wrote {output.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
