# File: cl.py.1shot.seq (Python 3.11)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: cl.py.1shot.das

'__pyarmor_enter_53734__(...)'
import sys
import time
bing_data = __pyarmor__(0, None, b'keyinfo', 1)
expired = int(__pyarmor__(1, None, b'keyinfo', 1))
version = f'''{sys.version_info[0]}.{sys.version_info[1]}'''
expired_str = time.strftime('%Y-%m-%d', time.localtime(int(expired))) if expired != -1 else ''
expired_str = '' if expired == -1 else f'''(过期时间: {expired_str})'''
bing_data = bing_data.decode()
if 'KCM' in bing_data:
    raise Exception('密钥错误，请重新获取')
print('Chanlun-Pro 缠论数据计算')
print('https://gitee.com/wang-student/chanlun-pro')
print(f'''运行环境: Python: {version}''')
print(f'''授权信息: {bing_data} {expired_str}''')
print(' *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * ')
'\n行情缠论数据计算\n\n* Github: https://github.com/yijixiuxin/chanlun-pro\n* gitee: https://gitee.com/wang-student/chanlun-pro\n'
from builtins import round as pyarmor__223, len as pyarmor__119, list as pyarmor__115, range as pyarmor__118, isinstance as pyarmor__109, dict as pyarmor__102, sorted as pyarmor__116, print as pyarmor__110, abs as pyarmor__172, int as pyarmor__108, bool as pyarmor__107, str as pyarmor__101, staticmethod as pyarmor__325, Exception as pyarmor__145, set as pyarmor__338
__author__ = 'wangxu'
import copy as copy
import datetime as datetime
import time as time
from typing import Dict as Dict, List as List, Tuple as Tuple, Union as Union
import numpy as np
import pandas as pd
import talib as ta
from tradingview_zy.cl_interface import BC as BC, BI as BI, FX as FX, ICL as ICL, LINE as LINE, MMD as MMD, TZXL as TZXL, XD as XD, XLFX as XLFX, ZS as ZS, CLKline as CLKline, Config as Config, Kline as Kline, compare_ld_beichi as compare_ld_beichi, query_macd_ld as query_macd_ld, user_custom_mmd as user_custom_mmd
__all__ = [
    'pd',
    'np',
    'ta',
    'copy',
    'datetime',
    'time',
    'Union',
    'List',
    'Dict',
    'Tuple',
    'ICL',
    'Config',
    'BI',
    'Kline',
    'CLKline',
    'LINE',
    'XD',
    'FX',
    'ZS',
    'MMD',
    'BC',
    'TZXL',
    'XLFX',
    'compare_ld_beichi',
    'user_custom_mmd',
    'query_macd_ld',
    'CL']

class CL(ICL):
    '''
    行情数据缠论分析
    '''
    '__pyarmor_enter_53736__(...)'
    
    def __init__(self, code, frequency, config, start_datetime):
        '''
        缠论计算
        :param code: 代码
        :param frequency: 周期
        :param config: 配置
        :param start_datetime: 开始分析的时间，不设置则分析计算所有
        '''
        '__pyarmor_enter_53738__(...)'
        self.code = code
        self.frequency = frequency
        self.config = copy.deepcopy(config) if config else { }
        self.start_datetime = start_datetime
    # WARNING: Decompyle incomplete

    
    def write_debug_log(self, msg):
        '__pyarmor_enter_53740__(...)'
        if self.debug:
            pyarmor__110(msg)
            return None

    
    def get_code(self):
        '__pyarmor_enter_53742__(...)'
        return self.code

    
    def get_frequency(self):
        '__pyarmor_enter_53744__(...)'
        return self.frequency

    
    def get_config(self):
        '__pyarmor_enter_53746__(...)'
        return self.config

    
    def get_src_klines(self):
        '__pyarmor_enter_53748__(...)'
        return self.src_klines

    
    def get_klines(self):
        '__pyarmor_enter_53750__(...)'
        if self.config['kline_type'] == Config.KLINE_TYPE_CHANLUN.value:
            _var_var_4 = []
            _var_var_5 = 0
            for _var_var_6 in self.cl_klines:
                _var_var_4.append(Kline(_var_var_5, _var_var_6.date, _var_var_6.h, _var_var_6.l, _var_var_6.o, _var_var_6.c, _var_var_6.a))
                _var_var_5 += 1
                return _var_var_4
                return self.src_klines

    
    def get_cl_klines(self):
        '__pyarmor_enter_53752__(...)'
        return self.cl_klines

    
    def get_idx(self):
        '__pyarmor_enter_53754__(...)'
        return self.idx

    
    def get_fxs(self):
        '__pyarmor_enter_53756__(...)'
        return self.fxs

    
    def get_bis(self):
        '__pyarmor_enter_53758__(...)'
        return self.bis

    
    def get_xds(self):
        '__pyarmor_enter_53760__(...)'
        return self.xds

    
    def get_zsds(self):
        '__pyarmor_enter_53762__(...)'
        return self.zsds

    
    def get_qsds(self):
        '__pyarmor_enter_53764__(...)'
        return self.qsds

    
    def get_bi_zss(self, zs_type):
        '__pyarmor_enter_53766__(...)'
    # WARNING: Decompyle incomplete

    
    def get_xd_zss(self, zs_type):
        '__pyarmor_enter_53768__(...)'
    # WARNING: Decompyle incomplete

    
    def get_zsd_zss(self):
        '__pyarmor_enter_53770__(...)'
        _var_var_7 = self.zsd_zss()
        _var_var_7 = pyarmor__115(pyarmor__116(_var_var_7, key = (lambda _z: _z.start.k.date)))
        for _var_var_8 in pyarmor__118(pyarmor__119(_var_var_7)):
            _var_var_7[_var_var_8].index = _var_var_8
            return _var_var_7

    
    def get_qsd_zss(self):
        '__pyarmor_enter_53772__(...)'
        _var_var_7 = self.qsd_zss()
        _var_var_7 = pyarmor__115(pyarmor__116(_var_var_7, key = (lambda _z: _z.start.k.date)))
        for _var_var_8 in pyarmor__118(pyarmor__119(_var_var_7)):
            _var_var_7[_var_var_8].index = _var_var_8
            return _var_var_7

    
    def get_last_bi_zs(self):
        '__pyarmor_enter_53774__(...)'
        _var_var_10 = None
        _var_var_11 = None
    # WARNING: Decompyle incomplete

    
    def get_last_xd_zs(self):
        '__pyarmor_enter_53776__(...)'
        _var_var_10 = None
        _var_var_11 = None
    # WARNING: Decompyle incomplete

    
    def _add_time(self, key, use_time):
        '''
        debug 增加用时
        '''
        '__pyarmor_enter_53778__(...)'
        if key not in self.use_time:
            self.use_time[key] = {
                'num': 1,
                'time': use_time }
            return None

    
    def default_bi_zs_type(self):
        '__pyarmor_enter_53780__(...)'
        return self.config['zs_bi_type'][0]

    
    def default_xd_zs_type(self):
        '__pyarmor_enter_53782__(...)'
        return self.config['zs_xd_type'][0]

    
    def process_klines(self, klines):
        '''
        计算k线缠论数据
        传递 pandas 数据，需要包括以下列：
            date  时间日期  datetime 格式
            high  最高价
            low   最低价
            open  开盘价
            close  收盘价
            volume  成交量

        可增量多次调用，重复已计算的会自动跳过，最后一个 bar 会进行更新
        '''
        '__pyarmor_enter_53784__(...)'
    # WARNING: Decompyle incomplete

    
    def process_idx(self):
        '''
        计算指标
        TODO 修改为全量计算，不再增量计算
        '''
        '__pyarmor_enter_53786__(...)'
        _var_var_24 = [
            'idx_macd_fast',
            'idx_macd_slow',
            'idx_macd_signal']
        _var_var_25 = 0
        for _var_var_2 in _var_var_24:
            _var_var_25 = max(_var_var_25, self.config[_var_var_2])
            _var_var_4 = self.get_klines()
            _var_var_26 = time.perf_counter()
            _var_var_25 = 500 + _var_var_25
        _var_var_25 = _var_var_25 if _var_var_25 <= pyarmor__119(_var_var_4) else pyarmor__119(_var_var_4)
        _var_var_27 = _var_var_4[-_var_var_25:]()
        self._add_time('process_idx_prices', time.perf_counter() - _var_var_26)
        _var_var_26 = time.perf_counter()
        (_var_var_28, _var_var_29, _var_var_30) = ta.MACD(np.array(_var_var_27), fastperiod = self.config['idx_macd_fast'], slowperiod = self.config['idx_macd_slow'], signalperiod = self.config['idx_macd_signal'])
        self._add_time('process_idx_ta_macd', time.perf_counter() - _var_var_26)
        _var_var_30 *= 2
        _var_var_28 = _var_var_28
        _var_var_29 = _var_var_29
        _var_var_30 = _var_var_30
        return True

    
    def process_cl_kline(self):
        '''
        根据最后一个 k 线，检查包含关系，生成缠论K线
        '''
        '__pyarmor_enter_53788__(...)'
        _var_var_4 = self.src_klines
        if pyarmor__119(_var_var_4) == 0:
            return False
        if pyarmor__119(self.cl_klines) == 0:
            _var_var_15 = _var_var_4[0]
            if _var_var_15.c > _var_var_15.o:
                _var_var_32 = CLKline(date = _var_var_15.date, k_index = _var_var_15.index, h = _var_var_15.h, l = _var_var_15.l, o = _var_var_15.l, c = _var_var_15.h, a = _var_var_15.a, klines = [
                    _var_var_15], _n = 1, _q = False, index = 0)
            else:
                _var_var_32 = CLKline(date = _var_var_15.date, k_index = _var_var_15.index, h = _var_var_15.h, l = _var_var_15.l, o = _var_var_15.h, c = _var_var_15.l, a = _var_var_15.a, klines = [
                    _var_var_15], _n = 1, _q = False, index = 0)
            self.cl_klines.append(_var_var_32)
        if pyarmor__119(self.cl_klines) >= 3:
            del self.cl_klines[-1]
            del self.cl_klines[-1]
        if pyarmor__119(self.cl_klines) > 0 and self.cl_klines[-1].k_index == -1:
            del self.cl_klines[-1]
        
        continue
        _var_var_33 = []
        for _var_var_2 in _var_var_4[::-1]:
            if _var_var_2.index > self.cl_klines[-1].klines[-1].index:
                _var_var_33.append(_var_var_2)
                continue
            _var_var_33 = _var_var_33[::-1]
            self._klines_baohan(_var_var_33, self.cl_klines)
            return True

    
    def process_fx(self):
        '''
        根据最后一个缠论K线，计算分型
        '''
        '__pyarmor_enter_53790__(...)'
        if pyarmor__119(self.cl_klines) < 3:
            return False
    # WARNING: Decompyle incomplete

    
    def process_bi(self):
        '''
        根据最后的分型，找到对应的笔
        '''
        '__pyarmor_enter_53792__(...)'
        if pyarmor__119(self.fxs) < 2:
            return False
    # WARNING: Decompyle incomplete

    
    def process_up_line(self, base_line_type):
        '''
        根据最后笔或线段，生成特征序列，计算高级别线段

        1. 生成特征序列
            1. 第一种情况，线段直接结束，从后续笔开始计算新的特征序列
            2. 第二种情况，线段标记未结束，找相反的特征序列，看是否有相反的顶底特征序列分型

        注意：
            1. 特征序列的包含，在正常情况，碰到后一笔完全包含前一笔（笔破坏），不处理包含关系
            2. 前特征序列包含后特征序列，进行包含处理，后续特征序列分型从包含的那一笔开始处理特征序列分型

        辅以 笔破坏 的判断进行线段划分 （设计开关）

        其他特殊处理：
            线段非最高最低点连接
            线段内中枢扩展
            线段内两中枢不同向

        其他约束条件：
            是否允许单笔成段
            是否允许有缺口的成段
        '''
        '__pyarmor_enter_53794__(...)'
        if base_line_type == 'bi':
            _var_var_54 = self.xds
            _var_var_55 = 'xd'
            _var_var_56 = self.bis
            _var_var_57 = self.default_xd_zs_type()
        elif base_line_type == 'xd':
            _var_var_54 = self.zsds
            _var_var_55 = 'zsd'
            _var_var_56 = self.xds
            _var_var_57 = Config.ZS_TYPE_BZ.value
        elif base_line_type == 'zsd':
            _var_var_54 = self.qsds
            _var_var_55 = 'qsd'
            _var_var_56 = self.zsds
            _var_var_57 = Config.ZS_TYPE_BZ.value
        else:
            raise '处理高级别线段类型错误：%s' % base_line_type
        if pyarmor__119(_var_var_56) < 3:
            return False
        if pyarmor__119(_var_var_54) == 0:
            _var_var_58 = self._xd_get_up_line_tzxl_info(_var_var_56, [], cal_type = [
                'di',
                'ding'])
            _var_var_59 = pyarmor__116(_var_var_58['di']['fxs'], key = (lambda _f: _f.low), reverse = False)
            _var_var_60 = pyarmor__116(_var_var_58['ding']['fxs'], key = (lambda _f: _f.high), reverse = True)
            for _var_var_61 in _var_var_60:
                for _var_var_62 in _var_var_59:
                    if _var_var_61.high >= _var_var_62.low and pyarmor__172(_var_var_61.xl.pre_line.index - _var_var_62.xl.pre_line.index) >= 2:
                        if _var_var_61.xl.pre_line.index > _var_var_62.xl.pre_line.index:
                            _var_var_63 = XD(start = _var_var_62.xl.line.start, end = _var_var_61.xl.pre_line.end, start_line = _var_var_62.xl.line, end_line = _var_var_61.xl.pre_line, _type = 'up', ding_fx = _var_var_61, di_fx = _var_var_62, index = 0, default_zs_type = _var_var_57)
                            _var_var_63.done = True if _var_var_61.done else False
                            _var_var_63.tzxls = _var_var_58['ding']['xls']
                            _var_var_54.append(_var_var_63)
                            return True
                        _var_var_63 = XD(start = _var_var_61.xl.line.start, end = _var_var_62.xl.pre_line.end, start_line = _var_var_61.xl.line, end_line = _var_var_62.xl.pre_line, _type = 'down', ding_fx = _var_var_61, di_fx = _var_var_62, index = 0, default_zs_type = _var_var_57)
                        _var_var_63.done = True if _var_var_62.done else False
                        _var_var_63.tzxls = _var_var_58['di']['xls']
                        _var_var_54.append(_var_var_63)
                        return True
                    if pyarmor__119(_var_var_54) == 0:
                        return False
                    self._process_line_hl(_var_var_54[-1], _var_var_55)
                    _var_var_26 = time.perf_counter()
                    _var_var_64 = _var_var_54[-1]
                    if self.config['__cal_xd_youhua'] and _var_var_64.end_line.index <= _var_var_56[-1].index and self._line_ukey(_var_var_64.end_line) == self._line_ukey(_var_var_56[_var_var_64.end_line.index]):
                        _var_var_65 = self._xd_get_up_line_tzxl_info(_var_var_56, _var_var_54, cal_type = [
                            'di',
                            'ding',
                            'line_di',
                            'line_ding'])
                        _var_var_66 = False
                        if pyarmor__119(_var_var_65['di']['fxs']) != 0 or pyarmor__119(_var_var_65['ding']['fxs']) != 0:
                            _var_var_66 = True
                        if (pyarmor__119(_var_var_65['line_ding']['fxs']) > 0 and _var_var_64.type == 'up' or pyarmor__101(_var_var_64.ding_fx) != pyarmor__101(_var_var_65['line_ding']['fxs'][-1]) or pyarmor__119(_var_var_65['line_di']['fxs']) > 0) and _var_var_64.type == 'down' and pyarmor__101(_var_var_64.di_fx) != pyarmor__101(_var_var_65['line_di']['fxs'][-1]):
                            _var_var_66 = True
                        if _var_var_66 is False:
                            self._add_time(f'''_process_up_line_skip_{base_line_type}''', time.perf_counter() - _var_var_26)
                            return False
        if pyarmor__119(_var_var_54) == 0:
            pass
        else:
            _var_var_64 = _var_var_54[-1]
            if _var_var_64.not_del:
                pass
            elif _var_var_64.is_done() is False and _var_var_64.is_qk() is False:
                del _var_var_54[-1]
                continue
            if _var_var_64.is_split != '':
                del _var_var_54[-1]
                continue
            if _var_var_64.end_line.index > _var_var_56[-1].index:
                del _var_var_54[-1]
                continue
            if self._line_ukey(_var_var_64.end_line) != self._line_ukey(_var_var_56[_var_var_64.end_line.index]):
                del _var_var_54[-1]
                continue
            if _var_var_64.ding_fx.get_last_xl().line.index > _var_var_56[-1].index:
                del _var_var_54[-1]
                continue
            if _var_var_64.di_fx.get_last_xl().line.index > _var_var_56[-1].index:
                del _var_var_54[-1]
                continue
            if _var_var_64.start.val != _var_var_56[_var_var_64.start_line.index].start.val:
                del _var_var_54[-1]
                continue
            if _var_var_64.end.val != _var_var_56[_var_var_64.end_line.index].end.val:
                del _var_var_54[-1]
                continue
        if pyarmor__119(_var_var_54) == 0:
            return True
        _var_var_46 = 0
        _var_var_67 = None
        _var_var_46 += 1
        if _var_var_46 > 25:
            _var_var_68 = 1
        if _var_var_46 > 50:
            raise pyarmor__145(f'''{self.code}-{self.frequency}:遇到无法处理的线段，跳过，基础线类型：{base_line_type}，时间：{self.src_klines[-1].date}''')
        if pyarmor__119(_var_var_54) == 0:
            pass
        elif pyarmor__119(_var_var_54) >= 2:
            if _var_var_54[-1].is_done():
                self._xd_done_pre_xd(_var_var_54)
            if _var_var_54[-2].is_split != '' and _var_var_54[-2].is_done() is False:
                _var_var_54[-2].done = True
        _var_var_64 = _var_var_54[-1]
        _var_var_64.start = _var_var_64.start_line.start
        _var_var_64.end = _var_var_64.end_line.end
        _var_var_69 = self._line_ukey(_var_var_54[-1])
        for _var_var_70 in _var_var_54[::-1]:
            if _var_var_70.is_done():
                pass
            elif _var_var_70.type == 'up' and _var_var_70.is_qk() and _var_var_70.is_done() is False:
                (__, _var_var_71) = self._xd_cal_line_xlfx(self._xd_get_up_line_next_line(_var_var_56, _var_var_70), fx_type = 'di', bh_type = 'bh')
                if pyarmor__119(_var_var_71) > 0 and (lambda .0: pass# WARNING: Decompyle incomplete
)(_var_var_71()) > 0:
                    _var_var_70.done = True
                continue
            if _var_var_70.type == 'down' and _var_var_70.is_qk() and _var_var_70.is_done() is False:
                (__, _var_var_72) = self._xd_cal_line_xlfx(self._xd_get_up_line_next_line(_var_var_56, _var_var_70), fx_type = 'ding', bh_type = 'bh')
                if pyarmor__119(_var_var_72) > 0 and (lambda .0: pass# WARNING: Decompyle incomplete
)(_var_var_72()) > 0:
                    _var_var_70.done = True
            if _var_var_69 != self._line_ukey(_var_var_54[-1]):
                continue
        _var_var_64 = _var_var_54[-1]
        if _var_var_64.end_line.index > _var_var_56[-1].index or self._line_ukey(_var_var_64.end_line) != self._line_ukey(_var_var_56[_var_var_64.end_line.index]):
            del _var_var_54[-1]
            continue
    # WARNING: Decompyle incomplete

    
    def process_zs(self, cal_line_types):
        '''
        根据最后一线（笔 or 线段），计算中枢
        '''
        '__pyarmor_enter_53796__(...)'
    # WARNING: Decompyle incomplete

    
    def create_zs(self, zs_type, zs, lines, max_line_num):
        '''
        根据线，获取是否有共同的中枢区间
        lines 中，第一线是进入中枢的，不计算高低，最后一线不一定是最后一个出中枢的，如果是最后一个出中枢的，则不需要计算高低点

        @param zs_type: 标记中枢类型（笔中枢 or 线段中枢）
        @param zs: 指定原中枢，可以为 None 表示计算新的中枢
        @param lines: 计算中枢需要的线段
        @param max_line_num: 中枢内包含最大线段数量
        '''
        '__pyarmor_enter_53798__(...)'
        _var_var_26 = time.time()
        if pyarmor__119(lines) <= 3:
            self._add_time('create_zs', time.time() - _var_var_26)
            return None
        _var_var_104 = []
        _var_var_105 = False
        _var_var_106 = self._cross_qujian(self._line_get_zs_hl(lines[1]), self._line_get_zs_hl(lines[2]))
    # WARNING: Decompyle incomplete

    
    def create_dn_zs(self, zs_type, lines, max_line_num, zs_include_last_line):
        '''
        计算端内同向中枢
        '''
        '__pyarmor_enter_53800__(...)'
        _var_var_7 = []
        if pyarmor__119(lines) < 4:
            return _var_var_7
        _var_var_117 = 0
        _var_var_118 = lines[_var_var_117:]
        if pyarmor__119(_var_var_118) == 0:
            pass
    # WARNING: Decompyle incomplete

    
    def process_mmd(self, line_types):
        '''
        计算背驰与买卖点
        '''
        '__pyarmor_enter_53802__(...)'
    # WARNING: Decompyle incomplete

    
    def beichi_line(self, pre_line, now_line):
        '''
        计算两线之间是否有背驰，两笔必须是同方向的，最新的线创最高最低记录
        背驰 返回 True，否则返回 False
        '''
        '__pyarmor_enter_53804__(...)'
        if pre_line.type != now_line.type:
            return False
        if pre_line.type == 'up':
            if now_line.high < pre_line.high or now_line.low < pre_line.low:
                return False
        if pre_line.type == 'down':
            if now_line.low > pre_line.low or now_line.high > pre_line.high:
                return False
        return compare_ld_beichi(pre_line.get_ld(self), now_line.get_ld(self), now_line.type)

    
    def beichi_pz(self, zs, now_line):
        '''
        判断中枢是否有盘整背驰，中枢最后一线要创最高最低才可比较
        '''
        '__pyarmor_enter_53806__(...)'
        if zs.lines[-1].index != now_line.index:
            return (False, None)
        if zs.type not in ('up', 'down'):
            return (False, None)
        if now_line.type == 'up' and max < (lambda .0: [ _var_var_107.high for _var_var_107 in .0 ])(zs.lines()):
            return (False, None)
        if now_line.type == 'down' and min > (lambda .0: [ _var_var_107.low for _var_var_107 in .0 ])(zs.lines()):
            return (False, None)
        _var_var_137 = compare_ld_beichi(zs.lines[0].get_ld(self), now_line.get_ld(self), now_line.type)
        return (_var_var_137, zs.lines[0])

    
    def beichi_qs(self, lines, zss, now_line):
        '''
        判断是否是趋势背驰，首先需要看之前是否有不重合的同向中枢，在进行背驰判断

        首先要有两个中枢，并且级别与方向要相同
        当前线的方向与中枢方向相同，并且线要最高或最低
        两个中枢之间的级别，与离开最后中枢的级别相同
        然后两个中枢之间，与最后离开中枢段进行背驰比较
        '''
        '__pyarmor_enter_53808__(...)'
        if pyarmor__119(zss) < 2:
            return (False, [])
        _var_var_138 = zss[-2]
        _var_var_139 = zss[-1]
        _var_var_140 = self.zss_is_qs(_var_var_138, _var_var_139)
    # WARNING: Decompyle incomplete

    
    def zss_is_qs(self, one_zs, two_zs):
        '''
        判断两个中枢是否能够组成趋势
        '''
        '__pyarmor_enter_53810__(...)'
        if one_zs.lines[-1].type != two_zs.lines[-1].type:
            return None
        if self.config['judge_zs_qs_level'] and one_zs.level != two_zs.level:
            return None
        if one_zs.zg < two_zs.zd:
            _var_var_147 = 'up'
        elif one_zs.zd > two_zs.zg:
            _var_var_147 = 'down'
        else:
            return None
        if self.config['zs_wzgx'] == Config.ZS_WZGX_ZGD.value:
            if _var_var_147 == 'up' and two_zs.zd <= one_zs.zg:
                return None
            if _var_var_147 == 'down' and two_zs.zg >= one_zs.zd:
                return None
        elif self.config['zs_wzgx'] == Config.ZS_WZGX_ZGGDD.value:
            if _var_var_147 == 'up' and two_zs.zd <= one_zs.gg:
                return None
            if _var_var_147 == 'down' and two_zs.zg >= one_zs.dd:
                return None
        elif self.config['zs_wzgx'] == Config.ZS_WZGX_GD.value:
            if _var_var_147 == 'up' and two_zs.dd <= one_zs.gg:
                return None
            if _var_var_147 == 'down' and two_zs.gg >= one_zs.dd:
                return None
        else:
            raise pyarmor__145('中枢类型配置错误')
        return _var_var_147

    
    def _bi_special_bi_split(self, bi):
        '''
        特殊笔处理，重叠K线超过设置后进行拆分
        '''
        '__pyarmor_enter_53812__(...)'
        if ',' not in self.config['bi_split_k_cross_nums']:
            return False
        _var_var_148 = pyarmor__108(self.config['bi_split_k_cross_nums'].split(',')[0])
        _var_var_149 = pyarmor__108(self.config['bi_split_k_cross_nums'].split(',')[1])
        _var_var_148 = max(13, _var_var_148)
        if _var_var_149 < 0 or _var_var_149 > 5:
            _var_var_149 = 1
        if _var_var_148 >= 99:
            return False
        _var_var_45 = self.fxs[bi.start.index + 1:bi.end.index]
        _var_var_150 = pyarmor__101(Config.FX_QJ_K.value)
        _var_var_151 = pyarmor__101(Config.FX_QY_THREE.value)
        if pyarmor__119(_var_var_45) < 3:
            return False
    # WARNING: Decompyle incomplete

    
    def _xd_get_up_line_tzxl_info(self, base_lines, up_lines, cal_type):
        '''
        计算给定类型的 线段后的 特征序列顶底分型
        '''
        '__pyarmor_enter_53814__(...)'
        if pyarmor__119(up_lines) == 0:
            _var_var_171 = base_lines
            _var_var_172 = base_lines
        else:
            _var_var_64 = up_lines[-1]
            _var_var_171 = self._xd_get_up_line_next_line(base_lines, _var_var_64)
            _var_var_172 = self._xd_get_up_line_next_line(base_lines, _var_var_64, is_next_line = False)
        (_var_var_82, _var_var_83) = self._xd_cal_line_xlfx(_var_var_171, fx_type = 'di', bh_type = 'no_bh', no_done_fx = True, three_fx = True) if 'di' in cal_type else ([], [])
        (_var_var_90, _var_var_91) = self._xd_cal_line_xlfx(_var_var_171, fx_type = 'di', bh_type = 'bh') if 'bh_di' in cal_type else ([], [])
        (_var_var_84, _var_var_85) = self._xd_cal_line_xlfx(_var_var_171, fx_type = 'ding', bh_type = 'no_bh', no_done_fx = True, three_fx = True) if 'ding' in cal_type else ([], [])
        (_var_var_92, _var_var_93) = self._xd_cal_line_xlfx(_var_var_171, fx_type = 'ding', bh_type = 'bh') if 'bh_ding' in cal_type else ([], [])
        (_var_var_86, _var_var_87) = self._xd_cal_line_xlfx(_var_var_172, fx_type = 'di', bh_type = 'no_bh', no_done_fx = True, three_fx = True) if 'line_di' in cal_type else ([], [])
        (_var_var_94, _var_var_95) = self._xd_cal_line_xlfx(_var_var_172, fx_type = 'di', bh_type = 'bh') if 'bh_line_di' in cal_type else ([], [])
        (_var_var_88, _var_var_89) = self._xd_cal_line_xlfx(_var_var_172, fx_type = 'ding', bh_type = 'no_bh', no_done_fx = True, three_fx = True) if 'line_ding' in cal_type else ([], [])
        (_var_var_96, _var_var_97) = self._xd_cal_line_xlfx(_var_var_172, fx_type = 'ding', bh_type = 'bh') if 'bh_line_ding' in cal_type else ([], [])
        return {
            'bh_line_ding': {
                'xls': _var_var_96,
                'fxs': _var_var_97 },
            'line_ding': {
                'xls': _var_var_88,
                'fxs': _var_var_89 },
            'bh_line_di': {
                'xls': _var_var_94,
                'fxs': _var_var_95 },
            'line_di': {
                'xls': _var_var_86,
                'fxs': _var_var_87 },
            'bh_ding': {
                'xls': _var_var_92,
                'fxs': _var_var_93 },
            'ding': {
                'xls': _var_var_84,
                'fxs': _var_var_85 },
            'bh_di': {
                'xls': _var_var_90,
                'fxs': _var_var_91 },
            'di': {
                'xls': _var_var_82,
                'fxs': _var_var_83 },
            'line_base_lines': _var_var_172,
            'next_base_lines': _var_var_171 }

    
    def _xd_add_up_line(self, base_line_type, base_lines, up_lines, default_zs_type, up_line_type, up_line, tzxlfx, tzxls, is_split, not_del, not_yx):
        '''
        新增一个线段方法
        '''
        '__pyarmor_enter_53816__(...)'
    # WARNING: Decompyle incomplete

    
    def _xd_update_tzfx(self, base_line_type, base_lines, up_lines, up_line_type, default_zs_type, up_line, tzxls, tzxlfx, is_split):
        '''
        更新线段的特征序列对象
        '''
        '__pyarmor_enter_53818__(...)'
        _var_var_173 = up_line.start_line
        _var_var_174 = tzxlfx.xl.pre_line
        if tzxlfx.done is False:
            _var_var_174 = _var_var_176[0]
        if _var_var_174.index < _var_var_173.index:
            raise pyarmor__145('线段结束位置不能小于线段起始位置')
        if up_line.type == 'up' and _var_var_174.high < _var_var_173.low:
            raise pyarmor__145('线段结束价格不能小于线段起始价格')
        if up_line.type == 'down' and _var_var_174.low > _var_var_173.high:
            raise pyarmor__145('线段结束价格不能大于线段起始价格')
        up_line.end_line = _var_var_174
        up_line.end = _var_var_174.end
        up_line.tzxls = tzxls
        up_line.done = True if tzxlfx.done and tzxlfx.qk is False else False
        up_line.is_split = is_split
        self._process_line_hl(up_line, up_line_type)
        self.process_zs([
            up_line_type])
        self.process_mmd([
            up_line_type])
        if up_line.start_line.type != up_line.end_line.type:
            raise pyarmor__145(f'''线段起始与结束方向不一致: {up_line}''')
        self._xd_check_and_split_up_line(base_line_type, base_lines, up_lines, default_zs_type, up_line_type, up_line)
        return up_line

    
    def _xd_line_to_tzxl(self, base_lines, bh_direction, _l):
        '__pyarmor_enter_53820__(...)'
        return TZXL(bh_direction, _l, base_lines[_l.index - 1], False, True)

    
    def _xd_check_and_split_up_line(self, base_line_type, base_lines, up_lines, default_zs_type, up_line_type, up_line):
        '''
        检查并分割线段
        段内中枢有超过9段的，或者内部有两个相反方向的中枢，或者有两个及以上的中枢并且中枢直接有重叠，进行拆分
        '''
        '__pyarmor_enter_53822__(...)'
        if pyarmor__119(up_lines) <= 1:
            return False
        (_var_var_177, _var_var_178, _var_var_179, _var_var_180) = self._xd_check_xd_is_ok(base_lines, up_line, base_lines[up_line.start_line.index:up_line.end_line.index + 1])
        if _var_var_177:
            return False
        (_var_var_181, _var_var_182) = self._xd_split_optimal_hl_ll(base_lines, up_line, _var_var_178, _var_var_179)
    # WARNING: Decompyle incomplete

    
    def _xd_check_xd_is_ok(self, base_lines, up_line, lines):
        '''
        检查给定的线列表能否组成线段
        返回值：
            1. 是否可组成线段
            2. 如果不可组成线段，进行拆分的话，向上线段的排列
            3. 如果不可组成线段，进行拆分的话，向下线段的排列
            4. 原因字符串
        '''
        '__pyarmor_enter_53824__(...)'
        if pyarmor__119(lines) in (1, 3, 5):
            return (True, [], [], '')
        if pyarmor__119(lines) % 2 == 0:
            return (False, [], [], '')
        _var_var_7 = self.create_dn_zs('bi', lines)
        _var_var_200 = []
        _var_var_201 = []
    # WARNING: Decompyle incomplete

    
    def _xd_done_pre_xd(self, up_lines):
        '''
        线段方法：将目前的线段全部标记为完成
        '''
        '__pyarmor_enter_53826__(...)'
        for _var_var_210 in up_lines:
            if _var_var_210.done is False:
                _var_var_210.done = True
            return True

    
    def _xd_get_up_line_next_line(self, base_lines, up_line, is_next_line):
        '__pyarmor_enter_53828__(...)'
        if up_line.type == 'up':
            if is_next_line:
                _var_var_211 = base_lines[up_line.ding_fx.xl.pre_line.index + 1:]
                if pyarmor__119(_var_var_211) == 0:
                    return []
                if _var_var_211[0].type == 'up':
                    del _var_var_211[0]
                else:
                    _var_var_211 = base_lines[up_line.di_fx.xl.pre_line.index + 1:]
            if pyarmor__119(_var_var_211) == 0:
                return []
            return _var_var_211
        if is_next_line:
            _var_var_211 = base_lines[up_line.di_fx.xl.pre_line.index + 1:]
            if pyarmor__119(_var_var_211) == 0:
                return []
            if _var_var_211[0].type == 'down':
                del _var_var_211[0]
            else:
                _var_var_211 = base_lines[up_line.ding_fx.xl.pre_line.index + 1:]
        if pyarmor__119(_var_var_211) == 0:
            return []
        return _var_var_211

    
    def _xd_split_optimal_hl_ll(self, base_lines, split_up_line, line_ups, line_downs):
        '''
        线段查找最优分割线
        '''
        '__pyarmor_enter_53830__(...)'
        if pyarmor__119(line_downs) >= 3 or pyarmor__119(line_ups) >= 3:
            pass
        else:
            return (None, None)
        _var_var_212 = base_lines[split_up_line.start_line.index:split_up_line.end_line.index + 1]
        _var_var_213 = (lambda .0: [ _var_var_107.high for _var_var_107 in .0 ])(_var_var_212())
        _var_var_214 = (lambda .0: [ _var_var_107.low for _var_var_107 in .0 ])(_var_var_212())
        if split_up_line.high != _var_var_213 or split_up_line.low != _var_var_214:
            if split_up_line.type == 'up':
                for _var_var_182 in line_downs:
                    for _var_var_181 in line_ups:
                        if _var_var_182.index > _var_var_181.index and _var_var_182.end.val < _var_var_181.end.val:
                            
                            
                            return None, min, (_var_var_181, _var_var_182)
                        if split_up_line.type == 'down':
                            for (lambda hl, ll: '__pyarmor_enter_53832__(...)'_var_var_217 = 0_var_var_217) in line_ups:
                                for None in line_downs:
                                    if _var_var_181.index > _var_var_182.index and _var_var_181.end.val > _var_var_182.end.val:
                                        
                                        
                                        return None, min, (_var_var_181, _var_var_182)
                                if split_up_line.type == 'up':
                                    for _var_var_182 in line_downs:
                                        for _var_var_181 in line_ups:
                                            if _var_var_182.index - _var_var_181.index >= 2 and _var_var_181.index - split_up_line.start_line.index >= 2 and split_up_line.end_line.index - _var_var_182.index >= 2 and _var_var_182.end.val < _var_var_181.end.val:
                                                _var_var_215.append({
                                                    'hl': _var_var_181,
                                                    'll': _var_var_182,
                                                    'diff_val': _var_var_216(_var_var_181, _var_var_182) })
                                            if split_up_line.type == 'down':
                                                for _var_var_181 in line_ups:
                                                    for _var_var_182 in line_downs:
                                                        if _var_var_181.index - _var_var_182.index >= 2 and _var_var_182.index - split_up_line.start_line.index >= 2 and split_up_line.end_line.index - _var_var_181.index >= 2 and _var_var_181.end.val > _var_var_182.end.val:
                                                            _var_var_215.append({
                                                                'hl': _var_var_181,
                                                                'll': _var_var_182,
                                                                'diff_val': _var_var_216(_var_var_181, _var_var_182) })
                                                        if pyarmor__119(_var_var_215) == 0:
                                                            return (None, None)
                                                        _var_var_215 = pyarmor__116(_var_var_215, key = (lambda _g: _g['diff_val']))
                                                        return (_var_var_215[0]['hl'], _var_var_215[0]['ll'])
                                                        return (None, None)

    
    def _xd_get_next_tzfx(self, dings, dis, find_type):
        '__pyarmor_enter_53834__(...)'
    # WARNING: Decompyle incomplete

    
    def _line_ukey(self, _l):
        '__pyarmor_enter_53836__(...)'
        _var_var_224 = f'''{_l.index}_{_l.start.k.date}_{_l.end.k.date}_{_l.start.val}_{_l.end.val}_{_l.start.index}_{_l.end.index}_{_l.start.done}_{_l.end.done}_{_l.is_done()}'''
        if pyarmor__109(_l, XD):
            _var_var_224 += '__start_line__' + self._line_ukey(_l.start_line) + '__end_line__' + self._line_ukey(_l.end_line) + '__xl_ding__' + self._line_ukey(_l.ding_fx.xl.pre_line) + '__xl_di__' + self._line_ukey(_l.di_fx.xl.pre_line)
        return _var_var_224

    __up_cross = (lambda one_list, two_list: '__pyarmor_enter_53838__(...)'# WARNING: Decompyle incomplete
)()
    __down_cross = (lambda one_list, two_list: '__pyarmor_enter_53840__(...)'# WARNING: Decompyle incomplete
)()
    
    def _lines_level_ld(self, lines):
        '''
        计算给定的线集合的力度
        '''
        '__pyarmor_enter_53842__(...)'
        if pyarmor__119(lines) == 0:
            return (None, None)
        if lines[0].type != lines[-1].type:
            return (None, None)
        _var_var_226 = (lambda .0: [ _var_var_107.high for _var_var_107 in .0 ])(lines())
        _var_var_227 = (lambda .0: [ _var_var_107.low for _var_var_107 in .0 ])(lines())
        if lines[0].type == 'up' and lines[0].low != _var_var_227:
            return (None, None)
        if lines[0].type == 'down' and lines[0].high != _var_var_226:
            return (None, None)
        if lines[-1].type == 'up' and lines[-1].high != _var_var_226:
            return (None, None)
        if lines[-1].type == 'down' and lines[-1].low != _var_var_227:
            return (None, None)
        if pyarmor__119(lines) == 1:
            return (1, query_macd_ld(self, lines[0].start, lines[-1].end))
        _var_var_228 = 0
        _var_var_229 = [
            lines[1].high,
            lines[1].low]
    # WARNING: Decompyle incomplete

    
    def _process_line_hl(self, line, line_type):
        '''
        处理并计算线（笔、线段）实际高低点
        '''
        '__pyarmor_enter_53844__(...)'
        if line_type == 'bi':
            _var_var_181 = self._line_qj(line, self.config['bi_qj'])
        elif line_type == 'xd':
            _var_var_181 = self._line_qj(line, self.config['xd_qj'])
        elif line_type == 'zsd':
            _var_var_181 = self._line_qj(line, self.config['zsd_qj'])
        elif line_type == 'qsd':
            _var_var_181 = self._line_qj(line, self.config['zsd_qj'])
        else:
            raise pyarmor__145('计算线段高低点，线的对象类型错误 %s' % line_type)
        line.high = _var_var_181[0]
        line.low = _var_var_181[1]
        if pyarmor__109(line, XD):
            line.start = line.start_line.start
            line.end = line.end_line.end
        _var_var_230 = self._line_zs_hl(line)
        line.zs_high = _var_var_230[0]
        line.zs_low = _var_var_230[1]
        return True

    
    def _fx_qj_high_low(self, start, end, _type):
        '''
        获取 分型区间 实际的 高低点
        '''
        '__pyarmor_enter_53846__(...)'
        _var_var_164 = min(start.k.klines[0].index, end.k.klines[-1].index)
        _var_var_165 = max(start.k.klines[0].index, end.k.klines[-1].index)
        _var_var_231 = min(start.k.index, end.k.index)
        _var_var_232 = max(start.k.index, end.k.index)
        if _type == 'k':
            _var_var_4 = self.src_klines[_var_var_164:_var_var_165 + 1]
        elif _type == 'ck':
            _var_var_4 = self.cl_klines[_var_var_231:_var_var_232 + 1]
        else:
            raise pyarmor__145('获取分型区间高低点类型错误 %s' % _type)
        _var_var_233 = (lambda .0: [ _var_var_2.h for _var_var_2 in .0 ])(_var_var_4())
        _var_var_234 = (lambda .0: [ _var_var_2.l for _var_var_2 in .0 ])(_var_var_4())
        return [
            _var_var_233,
            _var_var_234]

    
    def _line_zs_hl(self, _l):
        '__pyarmor_enter_53848__(...)'
        if self.config['zs_qj'] == Config.ZS_QJ_DD.value:
            return [
                _l.ding_high(),
                _l.di_low()]
        if self.config['zs_qj'] == Config.ZS_QJ_CK.value:
            return self._fx_qj_high_low(_l.start, _l.end, 'ck')
        if self.config['zs_qj'] == Config.ZS_QJ_K.value:
            return self._fx_qj_high_low(_l.start, _l.end, 'k')
        raise pyarmor__145('计算线的高低点类型错误：%s' % self.config['zs_qj'])

    
    def _line_get_zs_hl(self, _l):
        '__pyarmor_enter_53850__(...)'
        return [
            _l.zs_high,
            _l.zs_low]

    
    def _line_qj(self, line, qj_type):
        '''
        获取线的区间值
        '''
        '__pyarmor_enter_53852__(...)'
        if qj_type in (Config.BI_QJ_DD.value, Config.XD_QJ_DD.value, Config.ZSD_QJ_DD.value):
            return [
                line.ding_high(),
                line.di_low()]
        if qj_type in (Config.BI_QJ_CK.value, Config.XD_QJ_CK.value, Config.ZSD_QJ_CK.value):
            return self._fx_qj_high_low(line.start, line.end, 'ck')
        if qj_type in (Config.BI_QJ_K.value, Config.XD_QJ_K.value, Config.ZSD_QJ_K.value):
            return self._fx_qj_high_low(line.start, line.end, 'k')
        raise pyarmor__145('获取线段的区间，指定的类型错误 %s' % qj_type)

    
    def _process_dn_zs(self, lines, up_lines, zss, cal_line_type):
        '''
        计算端内的中枢
        '''
        '__pyarmor_enter_53854__(...)'
        _var_var_236 = up_lines[-2:-1]
        if pyarmor__119(_var_var_236) > 0:
            for _var_var_237 in _var_var_236:
                _var_var_238 = lines[_var_var_237.start_line.index:_var_var_237.end_line.index + 1]
                _var_var_235 = _var_var_238()
                _var_var_239 = zss()
                _var_var_240 = self.create_dn_zs(cal_line_type, _var_var_238, zs_include_last_line = False)
                for _var_var_241 in _var_var_239:
                    if (lambda .0: [ _var_var_245.start.index for _var_var_245 in .0 ]) not in _var_var_240():
                        _var_var_241.real = False
                        continue
                    for _var_var_242 in _var_var_240:
                        if _var_var_241.start.index == _var_var_242.start.index:
                            self._copy_zs(_var_var_242, _var_var_241)
                            _var_var_241.done = True
                        for _var_var_242 in _var_var_240:
                            if (lambda .0: [ _var_var_245.start.index for _var_var_245 in .0 ]) not in _var_var_239():
                                _var_var_242.index = zss[-1].index + 1 if pyarmor__119(zss) > 0 else 0
                                zss.append(_var_var_242)
        if pyarmor__119(_var_var_118) == 0:
            return False
        _var_var_243 = zss()
        _var_var_120 = self.create_dn_zs(cal_line_type, _var_var_118)
        for _var_var_244 in _var_var_243:
            if (lambda .0: [ _var_var_245.start.index for _var_var_245 in .0 ]) not in _var_var_120():
                _var_var_244.real = False
                continue
            for _var_var_242 in _var_var_120:
                if _var_var_242.start.index == _var_var_244.start.index:
                    self._copy_zs(_var_var_242, _var_var_244)
                for _var_var_242 in _var_var_120:
                    if (lambda .0: [ _var_var_245.start.index for _var_var_245 in .0 ]) not in _var_var_243():
                        _var_var_242.index = zss[-1].index + 1 if pyarmor__119(zss) > 0 else 0
                        zss.append(_var_var_242)
                    return True

    
    def _process_fl_zs(self, lines, up_lines, zss, cal_line_type):
        '''
        分类中枢，段内中枢的优化
        '''
        '__pyarmor_enter_53856__(...)'
    # WARNING: Decompyle incomplete

    
    def _process_bz_zs(self, lines, zss, cal_line_type):
        '''
        计算并处理标准中枢
        '''
        '__pyarmor_enter_53858__(...)'
        if pyarmor__119(zss) == 0:
            _var_var_249 = lines[-4:]
            _var_var_9 = self.create_zs(cal_line_type, None, _var_var_249)
            if _var_var_9:
                zss.append(_var_var_9)
            return True
        _var_var_10 = zss[-1]
        _var_var_118 = lines[_var_var_10.lines[0].index:]
        _var_var_250 = self.create_zs(cal_line_type, _var_var_10, _var_var_118)
    # WARNING: Decompyle incomplete

    
    def _process_fx_zs(self, lines, zss, cal_line_type):
        '''
        计算并处理方向性中枢
        '''
        '__pyarmor_enter_53860__(...)'
        if pyarmor__119(lines) < 5:
            return False
        if pyarmor__119(zss) > 0:
            del zss[-1]
        if pyarmor__119(zss) > 0:
            del zss[-1]
        _var_var_10 = None
        _var_var_37 = 0
        if pyarmor__119(zss) > 0:
            _var_var_10 = zss[-1]
            _var_var_37 = _var_var_10.lines[-1].index
        _var_var_119 = None
        _var_var_211 = lines[_var_var_37:]
        if pyarmor__119(_var_var_211) < 5:
            pass
    # WARNING: Decompyle incomplete

    
    def _bi_check_bi_fx_ok(self, start_fx, end_fx):
        '''
        检查笔的起始与结束分型是否符合要求
        '''
        '__pyarmor_enter_53862__(...)'
        if start_fx.type == end_fx.type:
            return False
        _var_var_254 = self.config['fx_qj']
        _var_var_255 = self.config['fx_qy']
        _var_var_256 = self.config['fx_check_k_nums']
        if self.config['bi_type'] in (Config.BI_TYPE_OLD.value, Config.BI_TYPE_NEW.value) and end_fx.k.k_index - start_fx.k.k_index < _var_var_256:
            if (start_fx.k.h > end_fx.k.h or start_fx.k.l < end_fx.k.l or start_fx.k.h < end_fx.k.h) and start_fx.k.l > end_fx.k.l:
                return False
        if start_fx.type == 'ding' and start_fx.k.h < end_fx.k.l:
            return False
        if start_fx.type == 'di' and start_fx.k.l > end_fx.k.h:
            return False
        if self.config['allow_bi_fx_strict'] is True and end_fx.k.k_index - start_fx.k.k_index < _var_var_256:
            if not start_fx.type == 'ding' or start_fx.low(_var_var_254, _var_var_255) < end_fx.low(_var_var_254, _var_var_255):
                if not start_fx.type == 'di' or start_fx.high(_var_var_254, _var_var_255) > end_fx.high(_var_var_254, _var_var_255):
                    if (end_fx.type == 'ding' or end_fx.low(_var_var_254, _var_var_255) < start_fx.low(_var_var_254, _var_var_255) or end_fx.type == 'di') and end_fx.high(_var_var_254, _var_var_255) > start_fx.high(_var_var_254, _var_var_255):
                        return False
                    if self.config['bi_fx_cgd'] == Config.BI_FX_CHD_NO.value:
                        _var_var_257 = (lambda .0: pass# WARNING: Decompyle incomplete
)(self.fxs[start_fx.index:end_fx.index + 1]())
                        _var_var_258 = (lambda .0: pass# WARNING: Decompyle incomplete
)(self.fxs[start_fx.index:end_fx.index + 1]())
                        if end_fx.k.k_index - start_fx.k.k_index < _var_var_256 and end_fx.type == 'ding' and end_fx.val < _var_var_257:
                            return False
                        if end_fx.k.k_index - start_fx.k.k_index < _var_var_256 and end_fx.type == 'di' and end_fx.val > _var_var_258:
                            return False
        if end_fx.type == 'ding' and self.config['fx_bh'] in (Config.FX_BH_DINGDI.value,) and end_fx.k.k_index - start_fx.k.k_index < _var_var_256 and end_fx.high(_var_var_254, _var_var_255) <= start_fx.high(_var_var_254, _var_var_255) and end_fx.low(_var_var_254, _var_var_255) >= start_fx.low(_var_var_254, _var_var_255):
            return False
        if end_fx.type == 'di' and self.config['fx_bh'] in (Config.FX_BH_DIDING.value,) and end_fx.k.k_index - start_fx.k.k_index < _var_var_256 and end_fx.high(_var_var_254, _var_var_255) <= start_fx.high(_var_var_254, _var_var_255) and end_fx.low(_var_var_254, _var_var_255) >= start_fx.low(_var_var_254, _var_var_255):
            return False
        if self.config['fx_bh'] in (Config.FX_BH_NO_QBH.value,) and end_fx.k.k_index - start_fx.k.k_index < _var_var_256 and start_fx.high(_var_var_254, _var_var_255) >= end_fx.high(_var_var_254, _var_var_255) and start_fx.low(_var_var_254, _var_var_255) <= end_fx.low(_var_var_254, _var_var_255):
            return False
        if self.config['fx_bh'] in (Config.FX_BH_NO_HBQ.value,) and end_fx.k.k_index - start_fx.k.k_index < _var_var_256 and end_fx.high(_var_var_254, _var_var_255) >= start_fx.high(_var_var_254, _var_var_255) and end_fx.low(_var_var_254, _var_var_255) <= start_fx.low(_var_var_254, _var_var_255):
            return False
        if self.config['fx_bh'] in (Config.FX_BH_NO.value,) and end_fx.k.k_index - start_fx.k.k_index < _var_var_256:
            if (end_fx.high(_var_var_254, _var_var_255) >= start_fx.high(_var_var_254, _var_var_255) or end_fx.low(_var_var_254, _var_var_255) <= start_fx.low(_var_var_254, _var_var_255) or end_fx.high(_var_var_254, _var_var_255) <= start_fx.high(_var_var_254, _var_var_255)) and end_fx.low(_var_var_254, _var_var_255) >= start_fx.low(_var_var_254, _var_var_255):
                return False
    # WARNING: Decompyle incomplete

    
    def _qk_num(self, klines):
        '''
        返回K线序列内的缺口数量
        '''
        '__pyarmor_enter_53864__(...)'
        _var_var_251 = 0
    # WARNING: Decompyle incomplete

    _copy_zs = (lambda copy_zs, to_zs: '__pyarmor_enter_53866__(...)'to_zs.zs_type = copy_zs.zs_typeto_zs.start = copy_zs.startto_zs.lines = copy_zs.linesto_zs.end = copy_zs.endto_zs.zg = copy_zs.zgto_zs.zd = copy_zs.zdto_zs.gg = copy_zs.ggto_zs.dd = copy_zs.ddto_zs.type = copy_zs.typeto_zs.line_num = copy_zs.line_numto_zs.level = copy_zs.levelto_zs.done = copy_zs.doneto_zs.real = copy_zs.real)()
    
    def _xd_cal_line_xlfx(self, lines, fx_type, bh_type, no_done_fx, three_fx):
        '''
        计算线的序列分型
        这里用线的 顶底高低点 计算特征序列

        fx_type : 制定特征序列的线段类型（ding 使用向下笔作为特征序列， di 使用向上笔作为特征序列）
        bh_type : 如果遇到一笔破坏（后一笔包含前一笔）是否处理包含关系
                    正常获取线段特征序列，使用 no_bh （不处理包含关系）
                    如遇到第二种情况，判断后续是否出现反向的特征序列分型，则需要使用 bh（处理包含关系）

        判断是否缺口，需要去除中间相反分型的特征序列

        no_done_fx 是否返回未完成的特征分型，默认是不返还
        three_fx 是否运行三笔成特征序列分型
        '''
        '__pyarmor_enter_53868__(...)'
        if pyarmor__119(lines) == 0:
            return ([], [])
        _var_var_264 = 'up' if fx_type == 'ding' else 'down'
        _var_var_265 = []
    # WARNING: Decompyle incomplete

    
    def _get_fx_qj_exists_qk(self, start_fx, end_fx):
        '''
        获取分型区间内的K线是否存在未回补的缺口
        '''
        '__pyarmor_enter_53870__(...)'
        if end_fx.index <= start_fx.index:
            return False
        _var_var_4 = self.src_klines[start_fx.k.k_index:end_fx.k.k_index + 1]
        _var_var_287 = False
        _var_var_288 = []
    # WARNING: Decompyle incomplete

    _cross_qujian = (lambda qj_one, qj_two: '__pyarmor_enter_53872__(...)'_var_var_294 = min(max(qj_two[0], qj_two[1]), max(qj_one[0], qj_one[1]))_var_var_295 = max(min(qj_two[0], qj_two[1]), min(qj_one[0], qj_one[1]))if _var_var_294 >= _var_var_295:
{
'max': _var_var_294,
'min': _var_var_295 })()
    
    def _create_fx(self, klines):
        '''
        根据传入的缠论K线，生成分型

        Args:
            klines (List[CLKline]): 缠论K线列表
        '''
        '__pyarmor_enter_53874__(...)'
        if pyarmor__119(klines) == 3:
            _var_var_296 = klines[0]
            _var_var_297 = klines[1]
            _var_var_298 = klines[2]
        elif pyarmor__119(klines) == 2:
            _var_var_296 = klines[0]
            _var_var_297 = klines[1]
            _var_var_298 = None
        else:
            return None
    # WARNING: Decompyle incomplete

    
    def _klines_baohan(self, klines, up_cl_klines):
        '''
        k线包含处理，返回缠论k线对象
        '''
        '__pyarmor_enter_53876__(...)'
    # WARNING: Decompyle incomplete


